# Generated by Django 5.0.4 on 2024-04-23 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_categorias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='tb_categoria',
        ),
    ]
