# Generated by Django 5.0.4 on 2024-06-01 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_categoria_id_alter_cliente_id_alter_produto_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='cliente',
        ),
    ]
