# Generated by Django 5.0.4 on 2024-06-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_vendas_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='produtos',
            field=models.ManyToManyField(related_name='vendasprodutos', through='store.VendaProduto', to='store.produto'),
        ),
    ]
