# Generated by Django 5.0.4 on 2024-06-02 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_despesa_fornecedor_investimento_vendas_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metodo', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Método de Pagamento',
                'verbose_name_plural': 'Métodos de Pagamento',
                'db_table': 'tb_metodos_pagamento',
                'ordering': ['metodo'],
            },
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('desconto_percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
                'db_table': 'tb_promocoes',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioVendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_relatorio', models.DateField()),
                ('total_vendas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_itens_vendidos', models.IntegerField()),
                ('relatorio_gerado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Relatório de Vendas',
                'verbose_name_plural': 'Relatórios de Vendas',
                'db_table': 'tb_relatorios_vendas',
                'ordering': ['-data_relatorio'],
            },
        ),
        migrations.CreateModel(
            name='LogAcao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Ação',
                'verbose_name_plural': 'Logs de Ação',
                'db_table': 'tb_logs_acoes',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('tipo_movimentacao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste')], max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'db_table': 'tb_movimentacoes_estoque',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('admin', 'Admin'), ('caixa', 'Caixa'), ('gerente', 'Gerente')], max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuário',
                'db_table': 'tb_perfis_usuarios',
                'ordering': ['usuario'],
            },
        ),
        migrations.CreateModel(
            name='AplicacaoPromocao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aplicado_em', models.DateTimeField(auto_now_add=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.vendas')),
                ('promocao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.promocao')),
            ],
            options={
                'verbose_name': 'Aplicação de Promoção',
                'verbose_name_plural': 'Aplicações de Promoção',
                'db_table': 'tb_aplicacoes_promocao',
                'ordering': ['aplicado_em'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoPagamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_transacao', models.DateTimeField(auto_now_add=True)),
                ('metodo_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.metodopagamento')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.vendas')),
            ],
            options={
                'verbose_name': 'Transação de Pagamento',
                'verbose_name_plural': 'Transações de Pagamento',
                'db_table': 'tb_transacoes_pagamento',
                'ordering': ['data_transacao'],
            },
        ),
    ]
